# ===== Debug Settings =====
COMM_DEBUG = False
AUDIO_DEBUG = False
COMM_PRINT_OK = False
DEBUG_COUNTRY = True
DEBUG_LED = False

SIMULATED_SERIAL = False

# ===== LOGARITHMIC SETTINGS =====
LOG_HGT = True
LOG_LED = False

# ===== COMMUNICATION SETTINGS =====
USE_LED_ARDUINO = True

# ===== Arduino Settings =====
ARDUINO_PORT_MAC = '/dev/cu.usbmodem142101'
ARDUINO_PORT_WINDOWS = 'COM5'
ARDUINO_PORT_WINDOWS2 = 'COM6'
ARDUINO_PORT_WINDOWSB = 'COM7'
ARDUINO_PORT_WINDOWSC = 'COM8'
ARDUINO_PORT_WINDOWSD = 'COM9'
ARDUINO_PORT_RASPI = '/dev/ttyACM0'
ARDUINO_PORT_RASPI2 = '/dev/ttyACM1'
ARDUINO_PORT_RASPI3 = '/dev/ttyUSB0'
ARDUINO_PORT_RASPI4 = '/dev/ttyUSB1'
BAUD_RATE = 115200
LOCAL_SEND_DELAY = .01     # in seconds

# ===== Incoming Messages Settings =====
HEADER_LENGTH = 3
TAIL_LENGTH = 3
INSTR_LENGTH = 3
MAX_DATA_SIZE = 1023

# ===== Electronic Mapping Settings Settings =====
PLATFORM_MINHEIGHT = 0
PLATFORM_MAXHEIGHT = 1000   # promille

LED_MINHEIGHT = 0
LED_MAXHEIGHT = 1000    # promille

MIN_MONEY = 0.01
MAX_MONEY = 1500

REEL_SPEED = 100

LED_IDLE_PATTERN = 0
LED_SPIN_PATTERN = 1

LED_WIN_PATTERN = 2

REEL_OFFSET = [
    0, # Country
    0, # Game
    0] # Year

# ===== Database Settings =====
COUNTRY_AMOUNT = 4
GAME_AMOUNT = 4
YEAR_AMOUNT = 7

# ===== Audio Constants =====
AUDIO_MUSIC = 0
AUDIO_RLOOP1 = 1
AUDIO_RLOOP2 = 2
AUDIO_RLOOP3 = 3
AUDIO_RSTP1 = 4
AUDIO_RSTP2 = 5
AUDIO_RSTP3 = 6
AUDIO_SHRED = 7
AUDIO_VICTORY = 8

SHRED_TIME_MIN = 3      # in seconds
SHRED_TIME_MAX = 10     # in seconds
